"""
export.py — Report Export Module

Exports generated narratives and evaluation metrics to Word (.docx) format.
"""

import io
import re
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH


def export_to_word(narrative, eval_metrics=None, query=None,
                   correction_log=None, title="Hierarchical Narrative Report"):
    """
    Export a narrative report to a Word (.docx) document.
    
    Args:
        narrative: The generated markdown narrative text
        eval_metrics: Dictionary of evaluation metrics
        query: The original user query
        correction_log: List of self-correction attempt logs
        title: Document title
        
    Returns:
        BytesIO buffer containing the Word document
    """
    doc = Document()
    
    # =========================================================
    # Styling
    # =========================================================
    style = doc.styles['Normal']
    font = style.font
    font.name = 'Calibri'
    font.size = Pt(11)
    
    # =========================================================
    # Title Page
    # =========================================================
    title_para = doc.add_heading(title, level=0)
    title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    doc.add_paragraph("Generated by Hierarchical Narrative Synthesis Engine")
    doc.add_paragraph("Deep Generative AI — Latent Representation Learning + Hierarchical Reasoning")
    
    if query:
        doc.add_paragraph("")
        q_para = doc.add_paragraph()
        q_run = q_para.add_run("Query: ")
        q_run.bold = True
        q_para.add_run(query)
    
    doc.add_page_break()
    
    # =========================================================
    # Evaluation Metrics Summary
    # =========================================================
    if eval_metrics:
        doc.add_heading("Evaluation Metrics", level=1)
        
        table = doc.add_table(rows=1, cols=2, style='Light Grid Accent 1')
        table.columns[0].width = Inches(3)
        table.columns[1].width = Inches(2)
        
        hdr_cells = table.rows[0].cells
        hdr_cells[0].text = "Metric"
        hdr_cells[1].text = "Score"
        
        metric_labels = {
            "vae_confidence": "VAE Confidence",
            "anomaly_likelihood": "Anomaly Score",
            "evidence_coverage": "Evidence Coverage",
            "faithfulness_score": "Faithfulness Score",
            "docs_referenced": "Documents Referenced",
            "total_docs": "Total Documents",
        }
        
        for key, label in metric_labels.items():
            val = eval_metrics.get(key)
            if val is not None:
                row = table.add_row().cells
                row[0].text = label
                if isinstance(val, float):
                    row[1].text = f"{val:.3f}"
                else:
                    row[1].text = str(val)
        
        # Critique
        critique = eval_metrics.get("critique")
        if critique and critique != "N/A":
            doc.add_paragraph("")
            c_para = doc.add_paragraph()
            c_run = c_para.add_run("Auditor Critique: ")
            c_run.bold = True
            c_para.add_run(critique)
        
        doc.add_paragraph("")
    
    # =========================================================
    # Self-Correction Log
    # =========================================================
    if correction_log and len(correction_log) > 1:
        doc.add_heading("Self-Correction Log", level=1)
        doc.add_paragraph(
            f"The system performed {len(correction_log)} generation attempt(s) "
            f"to meet quality thresholds."
        )
        
        table = doc.add_table(rows=1, cols=4, style='Light Grid Accent 1')
        hdr = table.rows[0].cells
        hdr[0].text = "Attempt"
        hdr[1].text = "Faithfulness"
        hdr[2].text = "Coverage"
        hdr[3].text = "Status"
        
        for entry in correction_log:
            row = table.add_row().cells
            row[0].text = str(entry["attempt"])
            row[1].text = f"{entry['faithfulness']:.3f}"
            row[2].text = f"{entry['coverage']:.3f}"
            row[3].text = "Passed" if entry["passed"] else "Rejected"
        
        doc.add_paragraph("")
    
    # =========================================================
    # Main Narrative Content
    # =========================================================
    doc.add_heading("Narrative Report", level=1)
    _markdown_to_docx(doc, narrative)
    
    # =========================================================
    # Footer
    # =========================================================
    doc.add_page_break()
    doc.add_heading("About This Report", level=2)
    doc.add_paragraph(
        "This report was automatically generated by the Hierarchical Narrative Synthesis system. "
        "The system uses a multi-layer pipeline: Semantic Embedding → Denoising Autoencoder → "
        "Variational Autoencoder → K-Means Clustering → Hierarchical Reasoning → "
        "LLM-based Narrative Synthesis → Self-Correction Evaluation."
    )
    
    # =========================================================
    # Save to buffer
    # =========================================================
    buffer = io.BytesIO()
    doc.save(buffer)
    buffer.seek(0)
    return buffer


def _markdown_to_docx(doc, markdown_text):
    """
    Convert basic Markdown text into Word document paragraphs.
    Handles headings (##), bold (**), bullet points (-), and plain text.
    """
    lines = markdown_text.split('\n')
    
    for line in lines:
        stripped = line.strip()
        
        if not stripped:
            doc.add_paragraph("")
            continue
        
        # Headings
        if stripped.startswith('### '):
            doc.add_heading(stripped[4:], level=3)
        elif stripped.startswith('## '):
            doc.add_heading(stripped[3:], level=2)
        elif stripped.startswith('# '):
            doc.add_heading(stripped[2:], level=1)
        
        # Bullet points
        elif stripped.startswith('- ') or stripped.startswith('* '):
            text = stripped[2:]
            para = doc.add_paragraph(style='List Bullet')
            _add_formatted_text(para, text)
        
        # Numbered lists
        elif re.match(r'^\d+[\.\)]\s', stripped):
            text = re.sub(r'^\d+[\.\)]\s', '', stripped)
            para = doc.add_paragraph(style='List Number')
            _add_formatted_text(para, text)
        
        # Regular paragraph
        else:
            para = doc.add_paragraph()
            _add_formatted_text(para, stripped)


def _add_formatted_text(paragraph, text):
    """
    Add text to a paragraph with basic bold (**text**) formatting support.
    """
    parts = re.split(r'(\*\*.*?\*\*)', text)
    for part in parts:
        if part.startswith('**') and part.endswith('**'):
            run = paragraph.add_run(part[2:-2])
            run.bold = True
        else:
            paragraph.add_run(part)
